#! /usr/bin/env bash

set -e

# Check if the argument is not provided
if [ -z "$1" ]; then
  echo "Argument not provided."
else
  export VPC_ID="$1"
fi

if [ -z "$2" ]; then
  echo "Argument not provided."
else
  export IGW_ID="$2"
fi

if [ -z "$3" ]; then
  echo "Argument not provided."
else
  export SUBNET_ID="$3"
fi

if [ -z "$4" ]; then
  echo "Argument not provided."
else
  export ASSOCIATE_ID="$4"
fi

if [ -z "$5" ]; then
  echo "Argument not provided."
else
  export ROUTE_TABLE_ID="$5"
fi

# Detaching the IGW
aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# Deleting IGW
aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

# Dissaociating subnet
aws ec2 disassociate-route-table --association-id $ASSOCIATE_ID

# Deleting subnet
aws ec2 delete-subnet --subnet-id $SUBNET_ID

# Deleting vpc
aws ec2 delete-vpc --vpc-id $VPC_ID